### ISSUE TITLE
Controllers and Models can't be published

### ISSUE THREAD

**Issue by uniqueginun** [bitfumes/laravel-multiauth#102]
**bug description**
there are no artisan command to publish controllers and models to edit them.

**Laravel Version**
7.5

**To Reproduce**
1. publish all publishable stuff like migrations and configs 
2. no controllers/models publishing command
3. therefore these two can not be edited

**Expected behavior**
controllers and model should be published as well as other stuff.

**Comment by anantgrafix** [comment]
There is no need to publish default controllers & models. if you need extra routes you can create new controller. and if you want to add models, you may create new and add in config file.
