### ISSUE TITLE
middleware role problem

### ISSUE THREAD

**Issue by MohammedJamal** [bitfumes/laravel-multiauth#106]
i have problem with my controller.my role name "editor" when i use $this->middleware('role:manager', ['only'=>'show']); allow to access to all function updat and create and store all, but when remove this part , ['only'=>'show'] the middleware work fine.

`<?php

namespace Bitfumes\Multiauth\Http\Controllers;

use App\Drug;
use App\scientificName;
use App\Company;
use App\Agency;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use Yajra\DataTables\ButtonsServiceProvider;
use Yajra\DataTables\Html;
use Yajra\DataTables\Html\Builder;
use Yajra\DataTables\Html\Column;
use Carbon\Carbon;
// use Yajra\DataTables\DataTables;
// use Datatable;

// use function PHPSTORM_META\type;

class DrugController extends Controller
{
    public function __construct()
    {
        // $this->middleware('role:super');
        $this->middleware('auth:admin');
        $this->middleware('role:manager', ['only'=>'show']);
        $this->adminModel = config('multiauth.models.admin');
    }

    public function index()
    {
        return view('multiauth::admin.drgs.index');
    }

    public function ajax()
    {
        $drugs = DB::table('drugs')
        ->join('companies', 'drugs.company_id', '=', 'companies.id')
        ->leftJoin('agencies', 'drugs.agency_id', '=', 'agencies.id')
        ->join('scientific_names', 'drugs.scientificdrugID', '=', 'scientific_names.id')
        ->select('drugs.*', 'companies.nameAR', 'companies.countryNameAR', 'agencies.fullNameAR','scientific_names.snameAR','scientific_names.snameEN','scientific_names.IndicationsforUseAr','scientific_names.IndicationsforUseEn');
        return Datatables::of($drugs)
        ->addColumn('action', function($drug) {
            return view('multiauth::admin.drgs.drugsaction', compact('drug'))->render();
        })
        ->toJson();
    }

    public function indexcompanies()
    {
        return view('multiauth::admin.drgs.comp');
    }

    public function ajaxcompanies()
    {
        $companies = Company::query();
        return Datatables::of($companies)
        ->addColumn('action', function($company) {
            return view('multiauth::admin.drgs.drugsaction', compact('company'))->render();
        })
        ->toJson();
    }

    public function createc()
    {
        return view('multiauth::admin.drgs.createfac');
    }

    public function storec(Request $request)
    {
        $company = Company::create([
            'nameAR'        => $request->nameAR,
            'nameEN'        => $request->nameEN,
            'countryNameAR' => $request->countryNameAR,
            'countryNameEn' => $request->countryNameEn,
        ]);
        return redirect(route('admin.factory'))->withSuccess(trans('app.success_store'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function editc(Company $company)
    {
        return view('multiauth::admin.drgs.editfac',compact('company'));
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function updatec(Request $request,Company $company)
    {
        $company->update($request->all());
        return redirect(route('admin.factory'))->withSuccess(trans('app.success_update'));
    }

    public function destroy($id)
    {
        //
    }
    
    public function destroyc(Company $company)
    {
        $company->delete();

        return redirect(route('admin.factory'))->withSuccess(trans('app.success_destroy'));
    }

    public function indexproxy()
    {
        return view('multiauth::admin.drgs.agen');
    }

    public function ajaxproxy()
    {
        $agencies = Agency::query();
        return Datatables::of($agencies)
        ->addColumn('action', function($agency) {
            return view('multiauth::admin.drgs.drugsaction', compact('agency'))->render();
        })
        ->toJson();
    }

    public function createa()
    {
        return view('multiauth::admin.drgs.createagen');
    }

    public function storea(Request $request)
    {
        $Agency = Agency::create([
            'fullnameAR'        => $request->fullnameAR,
            'fullnameEN'        => $request->fullnameEN,
            'shortnameAR'       => $request->shortnameAR,
            'shortnameEN'       => $request->shortnameEN,
        ]);
        return redirect(route('admin.proxy'))->withSuccess(trans('app.success_store'));
    }

    public function edita(Agency $agency)
    {
        return view('multiauth::admin.drgs.editagn',compact('agency'));
    }

    public function updatea(Request $request,Agency $agency)
    {
        $agency->update($request->all());
        return redirect(route('admin.proxy'))->withSuccess(trans('app.success_update'));
    }

    public function destroya(Agency $agency)
    {
        $agency->delete();

        return redirect(route('admin.proxy'))->withSuccess(trans('app.success_destroy'));
    }

}

`

**Comment by sarthaksavvy** [comment]
not able to recreate
