### ISSUE TITLE
Created A Test Controller Gives Not Found

### ISSUE THREAD

**Issue by SurajTiwari007** [bitfumes/laravel-multiauth#108]
I Just Created A New Controller Test Controller And Register A Route But While Writing admin/test it will give 404|Not Found 

Please Reply Me Fast

**Comment by sarthaksavvy** [comment]
Didi't get you.
Where you have written new routes ??

**Comment by SurajTiwari007** [comment]
admin.php

**Comment by anantgrafix** [comment]
shift your controller to **vendor\bitfumes\laravel-multiauth\src\Http\Controllers**

change namespace to **namespace Bitfumes\Multiauth\Http\Controllers;**

it will work fine.

**Comment by SurajTiwari007** [comment]
> shift your controller to **vendor\bitfumes\laravel-multiauth\src\Http\Controllers**
> 
> change namespace to **namespace Bitfumes\Multiauth\Http\Controllers;**
> 
> it will work fine.

thanks

**Comment by sarthaksavvy** [comment]
Closing this issue considering it is resolved.
