### ISSUE TITLE
Laravel 5.8 not working

### ISSUE THREAD

**Issue by itrabbi24** [bitfumes/laravel-multiauth#110]
Laravel 5.8 cannot support it.
when i 
"composer require bitfumes/laravel-multiauth"
in that time error.

**Comment by sarthaksavvy** [comment]
Show me error snapshot please

**Comment by itrabbi24** [comment]
![Capture2](https://user-images.githubusercontent.com/52894020/81464690-a6312b80-91e5-11ea-8d2e-0add1ad9d1f3.PNG)
