### ISSUE TITLE
middleware('password.confirm') not working

### ISSUE THREAD

**Issue by anantgrafix** [bitfumes/laravel-multiauth#111]
using Laravel 7.x
middleware('password.confirm') is not working with routes.

this middleware leads to Default login Page.

> 'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class

not getting Auth value.

I guess we need another middleware for the same. like **multiauth.password.confirm**

**Comment by sarthaksavvy** [comment]
there is no middleware called password.confirm
