### ISSUE TITLE
php artisan multiauth:make {guard} on laravel 7

### ISSUE THREAD

**Issue by rhivent** [bitfumes/laravel-multiauth#120]
Step 3. Routes for client is added to routes/client.php file

   ErrorException

  Undefined offset: 0

  at C:\laragon\www\rumahku\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:184
    180|             return;
    181|         }
    182|
    183|         preg_match('/\s+\/\*\*\n\s+\*\s(\w+\s)+"web"\s(\w+\s)+\w+.\n/', $provider, $match);
  > 184|         $provider = str_replace($match[0], $map . $match[0], $provider);
    185|         /********** Function Call **********/
    186|
    187|         $map_call = file_get_contents($this->stub_path . '/routes/map_call.stub');
    188|

  1   C:\laragon\www\rumahku\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:184
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "C:\laragon\www\rumahku\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php")

  2   C:\laragon\www\rumahku\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:56
      Bitfumes\Multiauth\Console\Commands\MakeMultiAuthCommand::registerRoutes()

**Comment by sarthaksavvy** [comment]
Updated for laravel 8 
please check

**Comment by metro-95** [comment]
Still getting Same error on Laravel 8. HELP Please!!

**Comment by metro-95** [comment]
Able to solve by Replacing the whole app/Providers/RouteServiceProvider.php file with 


<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * The path to the "home" route for your application.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        //

        parent::boot();
    }

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }

    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix('api')
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('routes/api.php'));
    }
}

**Comment by metro-95** [comment]
> 
> 
> Still getting Same error on Laravel 8. HELP Please!!

I was able to solve it by replacing app/Providers/RouteServiceProvider.php with same original file which was in a new laravel file not installed with multi-auth package

**Comment by dulsanSocioladder** [comment]
> > Still getting Same error on Laravel 8. HELP Please!!
> 
> I was able to solve it by replacing app/Providers/RouteServiceProvider.php with same original file which was in a new laravel file not installed with multi-auth package

can u describe me how you solve this brother???

**Comment by metro-95** [comment]
Generate a new laravel project and navigate to app/Providers and open RouteServiceProvider.php and copy all contents to the same file into your project you are working on.

**Comment by metro-95** [comment]
> 
> 
> > > Still getting Same error on Laravel 8. HELP Please!!
> > 
> > 
> > I was able to solve it by replacing app/Providers/RouteServiceProvider.php with same original file which was in a new laravel file not installed with multi-auth package
> 
> can u describe me how you solve this brother???

Generate a new laravel project and navigate to app/Providers and open RouteServiceProvider.php and copy all contents to the same file into your project you are working on.

**Comment by ItsSVK** [comment]
I did it manually, I was also getting the same error in laravel 7 to create another auth.
what I did was
I modified **handle() function** MakeMultiAuthCommand.php file located here
_vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php_
![Screenshot 2020-10-14 120700](https://user-images.githubusercontent.com/35792535/95952492-d379a980-0e15-11eb-8504-fcef61a96e5e.png)
and comment out the **registerRoutes() function**
now run this with your new guard

> php artisan multiauth:make {guard}

this will execute perfectly. but it won't execute step 4 which is _registering the new route file_
![Screenshot 2020-10-14 121353](https://user-images.githubusercontent.com/35792535/95953011-d32dde00-0e16-11eb-9c7b-2ff474863388.png)

after that open **RouteServiceProvider.php** located in
_app\Providers\RouteServiceProvider.php_
and override **map() function** and add **$this->mapStudentRoutes();** _[I created student auth,you put your auth guard]_
![Screenshot 2020-10-14 122236](https://user-images.githubusercontent.com/35792535/95954172-84814380-0e18-11eb-896d-06da51e514bf.png)

and also add the **mapStudentRoutes() function** below
![Screenshot 2020-10-14 122823](https://user-images.githubusercontent.com/35792535/95954355-cca06600-0e18-11eb-92af-c3846ad9e98b.png)
_don't forget to replace **student** with ur **guard name**_

now you are done. run 

> php artisan config:cache
> php artisan serve

and now open **127.0.0.1:8000/{guard}** in browser. If everything is right you will get the login page of that guard.

_and also after you done, don't forget to uncomment the **registerRoutes() function** in **MakeMultiAuthCommand.php** file_

Hope this helps. happy coding 🙂

**Comment by dulsanSocioladder** [comment]
Thanks Brother
________________________________
