### ISSUE TITLE
Loggin out a type of {guard} logs everything out on same browser

### ISSUE THREAD

**Issue by rodriguezwalter** [bitfumes/laravel-multiauth#121]
**Describe the bug**
When you log out certain guard, like admin or client it logs out the user also. I can replicate this over and over on same browser.

**Laravel Version**
7.1

**To Reproduce**
1. Go to 'register a custom guard, then log in and log out and the user is also logged out'

**Expected behavior**
Loggin out a client shoudnt log out a user.

**Comment by roydebangshu** [comment]
@rodriguezwalter 
### **Need to overwrite `logout() method` inside _login controller of each  guard_.**
```php
//LoginController.php

   public function logout(Request $request)
   {
      // Get the session key for this user
      $sessionKey = $this->guard()->getName();

      // Logout current user by guard
      $this->guard()->logout();

      // Delete single session key (just for this user)
      $request->session()->forget($sessionKey);//->invalidate();

      return $this->loggedOut($request) ?: redirect(route('admin.login'));
   }
```
