### ISSUE TITLE
Factory seed not working with laradock

### ISSUE THREAD

**Issue by gamenic-pawanrai** [bitfumes/laravel-multiauth#125]
Following the youtube video tutorial by the author. I implemented it in  laradock.

After  adding additional field `phone` in `admins` table migration and `AdminFactory.php`. I ran `php artisan multiauth:seed --role=super`

I get error:

> General error: 1364 Field 'phone' doesn't have a default value

though I have given value to `phone` field in `AdminFactory.php` it is not being inserted in the DB.

**Comment by sarthaksavvy** [comment]
Yes, package factory doesn't have phone field in the factory, you can't use seed of package
