### ISSUE TITLE
Still cannot assign model version 5.2.0

### ISSUE THREAD

**Issue by webleyson** [bitfumes/laravel-multiauth#139]
Describe the bug
In the docs it says you can set your own Admin model

https://bitfumes.github.io/laravel-multiauth/settings.html#models

I have set the following

'admin' => App\Admin::class,

But this has no affect. I have set in - vendors/config/auth.php and it sets.

What am I doing wrong?

Laravel Version
7.24

To Reproduce

Go to 'config/multiauth.php'
Set model to local model - app/Admin.php
     dd(Auth::guard('admin')->user());
See error - Not the App/Admin auth
Expected behavior
Expected to see admin from my app folder

**Comment by sarthaksavvy** [comment]
can you please try 5.2.1

**Comment by webleyson** [comment]
Hi there. Yes I have. Same problem!

**Comment by webleyson** [comment]
oh, 5.2.1?  OK. Will try. Thanks.

**Comment by sarthaksavvy** [comment]
Is it working ??

**Comment by webleyson** [comment]
Yes sir, it did!! Thankyou so much.
