### ISSUE TITLE
Publish the all files and assets

### ISSUE THREAD

**Issue by willmkt** [bitfumes/laravel-multiauth#30]
Is it possible to publish the all files and assets

I use a custom admin template and my projects always have various needs of customization.

Thanks.

**Comment by sarthaksavvy** [comment]
You mean the views related files?

**Comment by willmkt** [comment]
I mean views, controller, models, middleware.

All files related.

**Comment by sarthaksavvy** [comment]
If you want to have control on everything then you can create normal auth using command `php artisan multiauth:make guardname` and on multiauth config file you can turn admin section off.

In this way you will actually get everything on your project.

**Comment by tvnr690** [comment]
Sir if i want to change route view using controller.
how to publish all controllers used in multi-auth login package
