### ISSUE TITLE
Redirect to intended path after Multiauth login

### ISSUE THREAD

**Issue by aaranta** [bitfumes/laravel-multiauth#33]
The current Multiauth implementation is always redirect to route('admin.home') after login.
Refer sendLoginResponse function of vendor\bitfumes\laravel-multiauth\src\Http\Controllers\LoginController.php

If we want to redirect to intended path after multiauth login. How can we do it?

I tried to change sendLoginResponse function with the lines below:
//return redirect(route('admin.home'));
return $this->authenticated($request, $this->guard()->admin())
                ?: redirect()->intended($this->redirectPath());

But Laravel couldn't find admin(). What should be the correct implementation?
Could you please advise? Thanks.

**Comment by sarthaksavvy** [comment]
Where exactly you want to redirect after login?

**Comment by sarthaksavvy** [comment]
hey check this link, have updated the repo, https://github.com/bitfumes/laravel-multiauth#redirect-after-login

**Comment by aaranta** [comment]
Hi Sarthak, thanks for your reply.
I want to access a route guarded by Multiauth admin, but after login I was redirected to /admin/home which is not my intended URL.
For eg, I want to access http://mydomain.com/admin/mypath, which is guarded by Multiauth admin. After Multiauth admin login, I was redirected to http://mydomain.com/admin/home instead.

Is there a way to redirect to http://mydomain.com/admin/mypath after Multiauth login?
For Laravel normal auth, we could do that. Thanks.

**Comment by aaranta** [comment]
I managed to solve the issue by changing below:
sendLoginResponse function of vendor\bitfumes\laravel-multiauth\src\Http\Controllers\LoginController.php

//return redirect(route('admin.home'));
return redirect()->intended($default = '/admin/home');

Thanks!
