### ISSUE TITLE
How to override Multiauth controller & model class/method

### ISSUE THREAD

**Issue by aaranta** [bitfumes/laravel-multiauth#35]
Hi Sarthak,
I need to customize your Multiauth controller & model to suit my applications. Could you please teach me the proper way to override your controller & model class/method?

So far I've been editing your controller & model inside the vendor/bitfumes/ folder. But this is not a proper way as compoer update will overwrite my changes.

Thanks.

**Comment by aaranta** [comment]
Please close this issue. I think I should just use php artisan multiauth:make guardname.
Thanks!

**Comment by sarthaksavvy** [comment]
Yeah, great. Thanks for using this package.
