### ISSUE TITLE
Suggested Validation before publishing MultiAuth (custom gaurd)

### ISSUE THREAD

**Issue by akshay-bhagat** [bitfumes/laravel-multiauth#37]
**MultiAuth should check below items before publishing the custom guard** 
- [ ]  check if **Controller** with same name already exist?
- [ ]  check if  **Views** with same name already exist? 
- [ ]  check if **Database Factory** with same name already exist?
- [ ]  check if **Migration** file with same table name already exist?
- [ ]  check if  **Model** with same name already exist? 
- [ ]  check if **Middleware** with same name already exist?
- [ ]  check if **Notification** with same table name already exist?

Consider a scenario:
`
// creating a gaurd with name user, which is by default exists
 `
`$ php artisan multiauth:make user`

It will create _user_ table migration and other related files which can be repeated or overwrites existing files.. 
Below is one of the output of such scenario:
![image](https://user-images.githubusercontent.com/20301205/47949379-1b280300-df68-11e8-97e7-d83656fff583.png)

**Comment by sarthaksavvy** [comment]
Yes got your point, can you please tell me if this happened with `multiauth:make user` only or with any guard name?

**Comment by akshay-bhagat** [comment]
I have tested with `user` guard, but while creating some other guard, there is possibilities of having same name file generated by `multiauth:make {guard}` like Controller, view, model, etc. and it will be overwritten. (Thus loss of previous data.)

**Comment by sarthaksavvy** [comment]
Hey, I have fixed this problem, now if you run `make user` command then it will give error if already exist provider. 
Thanks for your effort.
