### ISSUE TITLE
How to update the package to add the redirection page

### ISSUE THREAD

**Issue by Rockersooraz** [bitfumes/laravel-multiauth#38]
![capture](https://user-images.githubusercontent.com/37184940/48041907-709e2300-e1a7-11e8-8828-f421fb0f7303.PNG)

**Comment by sarthaksavvy** [comment]
which redirection and where ?

**Comment by Rockersooraz** [comment]
the one that you upadated later.for those who have already used earlier where there was no direction option

**Comment by sarthaksavvy** [comment]
Why not update the package bro, you will get new functionality.
