### ISSUE TITLE
RegisterController can't find

### ISSUE THREAD

**Issue by jeraldpunx** [bitfumes/laravel-multiauth#45]
I want to edit the post of RegisterController but I can't find it.

`Route::post('register', 'Auth\RegisterController@register');`

and when I view the `app\Auth\RegisterController.php`, there is no register method.

**Comment by sarthaksavvy** [comment]
If you want completely change registration process, I would recommend you to create another guard instead of default admin.

If you just want to add any field then there is an option in the documentation, please check.

**Comment by sarthaksavvy** [comment]
You can create your own register method there. Just point out the register post route to your register method.

**Comment by jeraldpunx** [comment]
not working though, this is my files, it didn't even return me

`/app/Http/Controllers/Customer/Auth/RegisterController.php`

```
public function postRegistrationForm(Request $request)
{
    // return $request->all();
    var_dump($this->validator($request->all())->validate());

    return redirect()->route('login')
        ->with(['success' => 'Congratulations! your account is registered, you will shortly receive an email to activate your account.']);
}
```

and on my `routes\customer.php`
```
Route::group(['namespace' => 'Customer'], function() {
...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('customer.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('register', 'Auth\RegisterController@postRegistrationForm'); // <--------
...
});
```

It can run the route but it has different result. I can't get the `var_dump($this->validator($request->all())->validate());`
