### ISSUE TITLE
Getting Error While Installing Multi auth package

### ISSUE THREAD

**Issue by sanmitpawar** [bitfumes/laravel-multiauth#49]
Hello sarthak,

Before Installing Multi auth package in fresh laravel project i have already installed laravel auth by (php artisan make:auth) command for normal user and for admin part i have use multi auth install command (composer require bitfumes/laravel-multiauth) but i got 1 error in command line please check image below
![image](https://user-images.githubusercontent.com/19944808/51600654-7c88be00-1f28-11e9-8855-b436bb8ab29b.png)

![image](https://user-images.githubusercontent.com/19944808/51600723-a5a94e80-1f28-11e9-8791-3cd0bdb09ed4.png)

Please Help me with same ! 

Thank You
sanmit sanjay pawar
Email : sanmitpawar@gmail.com

**Comment by akshay-bhagat** [comment]
Probably you are getting **Access Denied** error which means your Laravel Framework directories/files don't have enough permission to write/execute.
Please check whether you have given **Read/Write/Execute** (recursive) permission to **bootstrap/** , **storage/** and **public/** directories inside your Laravel framework project and retry installing the package.
