### ISSUE TITLE
Getting Error page while deleting role assigned to any admin person

### ISSUE THREAD

**Issue by sanmitpawar** [bitfumes/laravel-multiauth#50]
Hello Sarthak,

I have created one role called editor and i have registered one admin into that role, but when i am trying to delete that role its giving me an laravel error page it should be me and same error in notification like format all other activities are giving
![image](https://user-images.githubusercontent.com/19944808/51739928-bd174180-20b8-11e9-90cc-66c1042bd404.png)

Error Page : 

![image](https://user-images.githubusercontent.com/19944808/51739966-d28c6b80-20b8-11e9-909b-7d09e91c530e.png)

Please Look into it and Fix !

Thank you & Regards
Sanmit Sanjay Pawar
sanmitpawar@gmail.com,

**Comment by sarthaksavvy** [comment]
Hey this is custom exception from package, you can not delete any role which is already assigned to any admin.

**Comment by neodavids** [comment]
I think the solution here is to remove the role from all the admins... then you can now delete. 
Right?
