### ISSUE TITLE
Class '\App\Consultant' not found

### ISSUE THREAD

**Issue by abdul191993** [bitfumes/laravel-multiauth#51]
when i register aany auth other then admin it display that error.
Class '\App\Consultant' not found
![capture](https://user-images.githubusercontent.com/47178064/52121131-58bc2b00-2640-11e9-933c-6af26b768c98.JPG)

**Comment by sarthaksavvy** [comment]
This is related to your laravel app I think, please try same process with fresh laravel app

**Comment by abdul191993** [comment]
Thanks issue solved
