### ISSUE TITLE
one login form for all auth's 

### ISSUE THREAD

**Issue by jettaz** [bitfumes/laravel-multiauth#53]
is there possible to make one login form for this ?

to chek first admin auth and then > another auth > users auth?? 
after login redirect to specific auth view ?

**Comment by Amrgumaa** [comment]
eager to see ur reply on that

**Comment by SidneyMachara** [comment]
i think it would be better to use radio button to let user select the type of auth they want to login as rather than                     -->  check first admin auth and then > another auth > users auth

**Comment by jettaz** [comment]
> i think it would be better to use radio button to let user select the type of auth they want to login as rather than --> check first admin auth and then > another auth > users auth

its a nice idea =)
