### ISSUE TITLE
Access forbidden! You don't have permission to access the requested directory.

### ISSUE THREAD

**Issue by ferdousanam** [bitfumes/laravel-multiauth#55]
When I have used `index.php` in the url the routes the `/admin` it works. But without using `index.php` it throws the problem. Can you please help me to solve the problem?

Note: I am using a shared hosting to deploy my project. I have changed the `root` directory to `public_html/public`. I have no SSH/Shell access.

![Shared Hosting Problem](https://user-images.githubusercontent.com/40851904/54944397-9a40c680-4f5d-11e9-8096-eade2a0011b9.png)

I have also faced the problem after using `php artisan serve` cmd in my local development environment but the problem is different. 

![Local delvelopment Env](https://user-images.githubusercontent.com/40851904/54944936-da547900-4f5e-11e9-8d75-068415f1e954.png)

**Comment by sarthaksavvy** [comment]
Please use php artisan serve to start server, don't use basic php style for routing
