### ISSUE TITLE
Getting the authenticated admin ID 

### ISSUE THREAD

**Issue by worldtok** [bitfumes/laravel-multiauth#56]
How do I get the authenticated admin ID.
Like in laravel Auth I can just do Auth:id().

**Comment by akshay-bhagat** [comment]
You can use Auth Guard as show below to get id of the authenticated admin...

`use Auth;`

`Auth::guard('admin')->user()->id; // this will return the id of authenticated admin` 

Syntax: Auth::guard('**guard_name**')->user()->**column_name**
