### ISSUE TITLE
Call to undefined method Bitfumes\Multiauth\Model\Admin::pullCache()

### ISSUE THREAD

**Issue by dr-amer** [bitfumes/laravel-multiauth#59]
when i try to logout that error generated "Call to undefined method Bitfumes\Multiauth\Model\Admin::pullCache()"

**Comment by sarthaksavvy** [comment]
Which version of laravel and which version of this package you are using?

**Comment by dr-amer** [comment]
laravel 5.8.15
![pullcache](https://user-images.githubusercontent.com/47056403/57690299-c83bb080-765a-11e9-9401-f07d014343d4.jpg)

**Comment by sarthaksavvy** [comment]
Try with fresh laravel app
