### ISSUE TITLE
Login using username instead of email id

### ISSUE THREAD

**Issue by mayurdere** [bitfumes/laravel-multiauth#61]
Thank you for this awesome package.
I have a column in admin table which is accepting username while registering the user.
Now I want username to be used with the password for the login instead of email which the package provides.
I am not receiving the emails too. And I want to change the user's password using the emails.

Regards,
-[Mayur](http://cuttingchai.info)

**Comment by sarthaksavvy** [comment]
This feature is not added yet, but I will add it to next release

**Comment by kmunirawi** [comment]
Great package, thank for the developers
What about this enhancement, does it added? 
Regards
