### ISSUE TITLE
Logout admin side automatically logged out the front user and vice versa

### ISSUE THREAD

**Issue by yasirijazpl** [bitfumes/laravel-multiauth#63]
I have two authentications system. One is this multi-auth for admin and other is laravel default auth for the front user. If logout from the front user, admin automatically get log out and vice versa.
For admin logout I am using route(admin.logout) and for front user, I am using route(logout)

**Comment by sarthaksavvy** [comment]
use auth('admin')->logout() function to logout only admin, it is already fixed in newer versions
