### ISSUE TITLE
 ErrorException  : Undefined offset: 0

### ISSUE THREAD

**Issue by shadracnicholas** [bitfumes/laravel-multiauth#64]
ErrorException  : Undefined offset: 0

  at C:\Users\Shadrac\Desktop\Projects\bimapay\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:183
    179|             return;
    180|         }
    181|
    182|         preg_match('/\s+\/\*\*\n\s+\*\s(\w+\s)+"web"\s(\w+\s)+\w+.\n/', $provider, $match);
  > 183|         $provider = str_replace($match[0], $map . $match[0], $provider);
    184|         /********** Function Call **********/
    185|
    186|         $map_call = file_get_contents($this->stub_path . '/routes/map_call.stub');
    187|

**Comment by sarthaksavvy** [comment]
Can you send me the error snapshot

**Comment by ItsSVK** [comment]
i am also having the same issue, don't know why its coming, tried almost everything, but no results! need help

**Comment by salahmyn** [comment]
I'm facing the same issue when creating a new guard
```

php artisan multiauth:make test
Step 1. Test Guard is added to config/auth.php file 

Step 2. New Controllers for Test is added to App\Http\Controller\{Test} 

Step 3. Routes for test is added to routes/test.php file 


   ErrorException  : Undefined offset: 0

  at D:\laragon\www\zeedweb\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:184
    180|         }
    181|
    182|         preg_match('/\s+\/\*\*\n\s+\*\s(\w+\s)+"web"\s(\w+\s)+\w+.\n/', $provider, $match);
    183|
  > 184|         $provider = str_replace($match[0], $map . $match[0], $provider);
    185|
    186|         /********** Function Call **********/
    187|
    188|         $map_call = file_get_contents($this->stub_path . '/routes/map_call.stub');

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "D:\laragon\www\zeedweb\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php")
      D:\laragon\www\zeedweb\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:184

  2   Bitfumes\Multiauth\Console\Commands\MakeMultiAuthCommand::registerRoutes()
      D:\laragon\www\zeedweb\vendor\bitfumes\laravel-multiauth\src\Console\Commands\MakeMultiAuthCommand.php:55

  Please use the argument -v to see more details.

```

The problem is with the lines below

```
   preg_match('/\s+\/\*\*\n\s+\*\s(\w+\s)+"web"\s(\w+\s)+\w+.\n/', $provider, $match);

   $provider = str_replace($match[0], $map . $match[0], $provider);


```

$match is an empty array 


Laravel Framework 5.7.28
"bitfumes/laravel-multiauth": "^1.0"

**Comment by sarthaksavvy** [comment]
Please try with new version, have some updates. If problem persists, please report again. Thanks for your support.
