### ISSUE TITLE
I want to use middleware for 2 roles in a single route 

### ISSUE THREAD

**Issue by mayurdere** [bitfumes/laravel-multiauth#66]
I want this route to be protected and can be viewd only to the admins with role 'dgs admin' and 'dgcomm admin'. I am trying this, but not working for both together.

Route::get('/incidentLog', function () {
    return view('incidents.incidentLog');
})->middleware('role:dgcomm admin', 'role:dgs admin');

**Comment by akshay-bhagat** [comment]
You can use Grouping to apply multiple middleware on routes..
ex: 
```
Route::middleware(['first', 'second'])->group(function () {
    Route::get('/', function () {
        // Uses first & second Middleware
    });

    Route::get('user/profile', function () {
        // Uses first & second Middleware
    });
}); 
```

**Reference link:** https://laravel.com/docs/5.8/routing#route-group-middleware

**Comment by mayurdere** [comment]
> You can use Grouping to apply multiple middleware on routes..
> ex:
> 
> ```
> Route::middleware(['first', 'second'])->group(function () {
>     Route::get('/', function () {
>         // Uses first & second Middleware
>     });
> 
>     Route::get('user/profile', function () {
>         // Uses first & second Middleware
>     });
> }); 
> ```
> 
> **Reference link:** https://laravel.com/docs/5.8/routing#route-group-middleware

Even this doesnt work

**Comment by sarthaksavvy** [comment]
New in `v3.0.0`:

Now you can use multiauth role and also permissions

I think this solved the issue
