### ISSUE TITLE
How to permit 'verify email' 

### ISSUE THREAD

**Issue by beulah019** [bitfumes/laravel-multiauth#67]
Hi, I truly love your multi Auth package, but i am having a hard time adding the verify email feature to the new auth i created. I know i have to do this  Auth::routes(['verify' => true]) in my 'web route' for normal user,
but where do i put this in the new auth, since the all routes are place in a group under the auth namespace..

**Comment by sarthaksavvy** [comment]
it is fixed in new version, if you still face any problem please open another issue here

**Comment by ipeyato** [comment]
I've install a new version, but new user still redirect to dashboard after register instead show notification to verify email address.
