### ISSUE TITLE
controller files not available

### ISSUE THREAD

**Issue by Kingabbas85** [bitfumes/laravel-multiauth#70]
why i cant see any controller files in the app/http/controllers of this package

**Comment by Kingabbas85** [comment]
plz explain it to me

**Comment by Kingabbas85** [comment]
> why i cant see any controller files in the app/http/controllers of this package

**Plz explain me this**

**Comment by sarthaksavvy** [comment]
Bro all the controllers are available on vendor/bitfumes/laravel-multiauth directory, and you can't publish controllers. If you want to edit then publish route and give your own controller there.
