### ISSUE TITLE
Controller files not published

### ISSUE THREAD

**Issue by Govar-Web** [bitfumes/laravel-multiauth#73]
thank u for this package it is so helpful!
Please add command to publish a controller files to default controller.
i want to add/edit mutliauth controllers but it is difficult to me every time go to vendor and edit files.

**Comment by tabirkeland** [comment]
@Govar-Web a simple solution would be to look at the [routes](https://github.com/bitfumes/laravel-multiauth/blob/master/src/routes/routes.php) to see what Controllers are being called.  Then create a custom controller and extend it in your application.  Last, redefine the route to point at your controller.

If that doesn't do it, try not discovering this package assets by updating your `composer.json`:
`"extra": {
    "laravel": {
        "dont-discover": [
            "bitfumes/laravel-multiauth"
        ]
    }
},`

**Comment by sarthaksavvy** [comment]
You can publish routes and then change controller

`php artisan vendor:publish --tag="multiauth:routes"
`
