### ISSUE TITLE
Error => Call to undefined function Bitfumes\Multiauth\Exception\array_get()

### ISSUE THREAD

**Issue by newtowebdevelopment** [bitfumes/laravel-multiauth#74]
I've installed a the latest bitfumes/laravel-multiauth  in to Laravel/framework version ^6.0.

Once I'm logged in everything works okay but when logged out and  visit lets say "/admin/show" it gives an error instead of redirecting to /admin.

![image](https://user-images.githubusercontent.com/50173896/64548518-add2c480-d326-11e9-8a7f-e4aef2bef6c2.jpg)

I've used previous bitfumes/laravel-multiauth  versions on previous Laravel?framework versions and and works with no errors.

Not sure if is a bug somewhere or if is it me. I would appreciate your help.

PS: Your package is amazing, it takes a lot of headache.

Thanks

**Comment by sarthaksavvy** [comment]
Thanks let me check this

**Comment by sarthaksavvy** [comment]
this issue is solved with new version, thanks for your support
