### ISSUE TITLE
FatalThrowableError: Call to undefined function str_plural()

### ISSUE THREAD

**Issue by hirwaf** [bitfumes/laravel-multiauth#75]
Laravel: 6.0
PHP: 7.3.9
Database: Ver 15.1 Distrib 10.3.17-MariaDB

### Description
When running `php artisan multiauth:make` I'm getting Fatal Error
due to `str_plural()` helper that used in `MakeMultiAuthCommand.php line 99`

**Comment by sarthaksavvy** [comment]
fixed with new version, thanks for information

**Comment by SarwarAhmed** [comment]
The solution is  ```Str::plural()```
It's works for me.
