### ISSUE TITLE
Adding multiple roles in a middleware

### ISSUE THREAD

**Issue by newtowebdevelopment** [bitfumes/laravel-multiauth#81]
Hi,

How can I add multiple roles in a middleware i.e:

    Route::group([
        'prefix'     => '/brands',
        'middleware' => ['role:super-admin, admin']
        ], function(){
        Route::get('/', 'Admin\BrandController@index')->name('brand.index');
    });

This is possible in the blade files like so @admin('emails,super-admin'), but I don't seem to be able to recreate in the routes.

Any help is much appreciated.

Thanks in advance.

**Comment by sarthaksavvy** [comment]
You mean multiple role in route middleware ?

**Comment by newtowebdevelopment** [comment]
Yes! I've tried everything but I don't seem to find a solution without assigning the roles to the user - I would rather assign multiple roles to the route if that's possible.

Thank you so much.

**Comment by sarthaksavvy** [comment]
Solved in new version 3.0.0 :)
