### ISSUE TITLE
Issue in hiding section for differet role

### ISSUE THREAD

**Issue by anuragarena** [bitfumes/laravel-multiauth#84]
@admin('distributor')
    <button>Only For Distributor</button>
@endadmin

want to show a button for admin with role of distributor. But after writing the above code, button is still visible to admin of other role like super, admin, etc. Whereas 

@admin('super')
    <button>Only For Super</button>
@endadmin

works fine (visible to admin with role of super only).

**Comment by sarthaksavvy** [comment]
Okay I will check this issue.
Thanks

**Comment by sarthaksavvy** [comment]
solved in new version :)

**Comment by anuragarena** [comment]
Thanks a lot but after I run command* php artisan multiauth:install  *The
command "vendor:publish --tag=multiauth:config" does not exist. issue pops
out. Attaching screenshot for reference.

**Comment by sarthaksavvy** [comment]
Please make sure you update with new version for use `install` command.

can you please send me a screenshot of error

**Comment by anuragarena** [comment]
*Dear Sarthak,*

              My composer is updated. Also I have created a new project
with Laravel 5.6. My current version is ( Laravel Framework 5.6.39 ). Also
I have setup the database connection correctly. Again attaching the
screenshot of the issue. Kindly look into it.

Thanks and Regards,

Anurag Ghosh

**Comment by anuragarena** [comment]
Dear *Sarthak,*

I would like to have an update for the solution of the previous mentioned
issue.
Thanks & Regards,
* Anurag Ghosh*

**Comment by rebarhama** [comment]
Dear Sarthak, 
 first of all, thank you for your amazing package.
I have the same bug with the latest version of your package(bitfumes/laravel-multiauth": "^5.0), do you have any solution?
