### ISSUE TITLE
Error when register new admin in postgresql

### ISSUE THREAD

**Issue by diskominfogithub** [bitfumes/laravel-multiauth#86]
hello dev..

I get this error 

"SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "" (SQL: select count(*) as aggregate from "admins" where "email" = admin_bpkad@super.com and "id" <> )"

when i try to register new admin using postgresql database..

**Comment by sarthaksavvy** [comment]
Thanks for this, I will check it over `PostgresSQL`
Have you tried it on `mysql` ?

**Comment by diskominfogithub** [comment]
> Thanks for this, I will check it over `PostgresSQL`
> Have you tried it on `mysql` ?

yes, it's work perfectly on "mysql"

**Comment by sarthaksavvy** [comment]
which version of PostgreSQL you have?

**Comment by diskominfogithub** [comment]
Postgresql v11.6
