### ISSUE TITLE
authority which gives you a flexible way to add role-based permissions to your project menu 

### ISSUE THREAD

**Issue by sanmitpawar** [bitfumes/laravel-multiauth#87]
Hello sir,

Multiauth package is very useful for me, I have used it in my so many projects. only one thing is if you can add authority which gives you a flexible way to add role-based permissions to your project menu. that would be a more extensive and helpful feature for us!

for example if we have a menu like

1) product
2) revenue
3) customers

so if we have an authority which menu (or route) is available for which role to access

**Comment by sarthaksavvy** [comment]
hey, have you used new version which  includes permissions also.
check out new docs http://bitfumes.github.io/laravel-multiauth

**Comment by sanmitpawar** [comment]
> hey, have you used new version which includes permissions also.
> check out new docs http://bitfumes.github.io/laravel-multiauth

sure
