### ISSUE TITLE
Implementing Email verification for another auth

### ISSUE THREAD

**Issue by Sadicko** [bitfumes/laravel-multiauth#92]
I have created another auth and I want to implement email verification but I am not using the default registration controller and I implement mine. How do I call the must verify email for this custom auth. How do I also call the "verified" middleware for the routes? I have gone through some of the issues but not getting the solution

**Comment by sarthaksavvy** [comment]
Okay, I will check.

Please provide laravel version you are using

**Comment by Sadicko** [comment]
I am using Laravel 7

**Comment by sarthaksavvy** [comment]
fixed with latest version 4.1.0
