### ISSUE TITLE
Email Verification in {guard} not working

### ISSUE THREAD

**Issue by anantgrafix** [bitfumes/laravel-multiauth#94]
**Describe the bug**
After installing {guard} by
php artisan multiauth:make student

Email Verification for that is not working.
If it is working, kindly provide detail in the discription.

P.S. i have not installed auth system provided by default laravel system.

**Laravel Version**
7.0

**Comment by 6lackManta** [comment]
Same issue here..

**Comment by sarthaksavvy** [comment]
Thanks for informing, I will check it and respond here

**Comment by sarthaksavvy** [comment]
fixed with latest version 4.1.0
