### ISSUE TITLE
Is it possible to redirect admin on the basis of their roles. Like each role has it's own CMS? And how we can publish the controller files of superadmin to app/controllers so that we can customize them according to our needs? 

### ISSUE THREAD

**Issue by 6lackManta** [bitfumes/laravel-multiauth#95]
**Describe the bug**

**Laravel Version**
Which laravel version you are using

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sarthaksavvy** [comment]
Hey, it is possible to control admin behavior, you can publish routes file and then create your own controller and link that in published route file.

Try to extend package controller for each new controller you make.
