### ISSUE TITLE
email field is not validating in blade template

### ISSUE THREAD

**Issue by anantgrafix** [bitfumes/laravel-multiauth#98]
First of all, Thanks Sarthak for this multiauth system.

we fount a bug, while adding admin one can accidentally text which is not email. we don't know how it was happened, we are using chrome
![Capture](https://user-images.githubusercontent.com/62057558/77796893-27998800-7096-11ea-817d-9c4159c79b50.JPG)
.

**Comment by sarthaksavvy** [comment]
Validations are there to check for email, no issue on package


how this happens??
