### ISSUE TITLE
Add details about Supper Admin

### ISSUE THREAD

**Issue by anantgrafix** [bitfumes/laravel-multiauth#99]
Most of us know this by watching your videos in youtube that how to create SupperAdmin again.

But there is no guidance in Documentation to create SupperAdmin again after executing command **pa migrate:fresh** 

Kindly add this in documentation.

P.S. Thanks for Your new Video Series about Laravel 7.

**Comment by sarthaksavvy** [comment]
You can create an superadmin by using `php artisan multiauth:role rolename` command
